config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resource :logins, only: [:new, :create ]
  resource :registrations, only: [:new, :create]
  resources :posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :name, :password, presence: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  
  def new
    @user = User.create
  end

  def create
    @user = User.find_by(login_params)
    if @user
      session[:current_user] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Invalid credentials"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def login_params
    params.require(:user).permit(:email, :password)
  end
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def new
    @user = User.create
  end

  def create
    @user = User.find_by(login_params)
    if @user
      session[:current_user] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Invalid credentials"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to root_path, status: :see_other
  end

  private

  def login_params
    params.require(:user).permit(:email, :password)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post,  only: %i[show edit update]

  def index
    user = User.find_by(id: session[:current_user])
    if user.blank?
      flash[:notice] = "Welcome dear guest"
    else
      flash[:notice] = "Welcome #{user.name}"
    end
    @posts = Post.all.order(created_at: "DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:current_user]
    if @post.save
      flash[:alert] = "Post successfully created"
      redirect_to root_path
    else
      flash[:alert] = "Can't create this post : " + @post.errors.full_messages.to_s
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
    if @post.user_id != session[:current_user]
      flash[:alert] = "You may not update this post"
      redirect_to root_path
    end
  end

  def update

    if @post.user_id != session[:current_user]
      flash[:alert] = "Operation not allowed"
      redirect_to root_path and return
    end 

    if @post.update(post_params)
      flash[:alert] = "Post successfully updated"
      redirect_to root_path
    else
      flash[:alert] = "Can't update this post : " + @post.errors.full_messages.to_s
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Successfully created"
      redirect_to root_path
    else
      flash[:alert] = "Can't create this user"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:alert] = "Successfully created"
      session[:current_user] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Can't create this user"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mixblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <%= notice%><br/>
      <%= alert %></div>
    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<h1>Login</h1>

<%= form_with model: @user, url: login_index_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
     <%= form.password_field :password %>
  </div>
  <div>
    <%=  form.submit "Login" %>
  </div>
<% end %>

app/views/logins/new.html.erb
<h1>Login</h1>

<%= form_with model: @user, url: logins_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
     <%= form.password_field :password %>
  </div>
  <div>
    <%=  form.submit "Login" %>
  </div>
<% end %>

<p>Don't have an account ? Please <%= link_to "Sign Up", new_registrations_path %> to create or edit Posts.</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with model: @post, url: post_path do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>
  <div>
    <%=  form.submit "Update post" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Created At</th>
    <th></th>
  </tr>
  <% if @posts.blank? %>
    <tr><td>No post at the moment</td></tr>
  <% end %>
   <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
       <td><%= post.user.name %></td>
       <td><%= post.created_at %></td>
       <td> <%= link_to "Show", post_path(post)  %></td>
    </tr>
  <% end %>
</table>

  <% if session[:current_user] %>
    <%= link_to "Create your own post", new_post_path %>
    <%= link_to "Logout", logins_path, data: { "turbo-method": :delete }  %>
  <% else %>
    <div>Want to add posts or edit yours ? Please <%= link_to "Sign In", new_logins_path %></p>
  <% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post, url: posts_path do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>
  <div>
    <%=  form.submit "Save post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1>Show post</h1>
<p>Title : <%= @post.title %></p>
<p>Body : <%= @post.body %></p>
<p>Author : <%= @post.user.name %></p>
<p>Created at : <%= @post.created_at %></p>
<% if @post.user.id == session[:current_user] %>
  <%= link_to "Edit", edit_post_path(@post) %>
<% end %>
<%= link_to "Home", root_path %>